import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "cats",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <p>고양이에 대한 모든 것!</p>
        <ul>
          <li>
            <a href="/ssg">SSG</a>
          </li>
          <li>
            <a href="/isr">ISR</a>
          </li>
          <li>
            <a href="/ssr">SSR</a>
          </li>
          <li>
            <a href="/csr">CSR</a>
          </li>
        </ul>
        {children}
      </body>
    </html>
  );
}
