import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "cats",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <p>고양이에 대한 모든 것!</p>
        <div>
          <Link href="/ssg" className="p-4">
            SSG
          </Link>
          <Link href="/isr" className="p-4">
            ISR
          </Link>
          <Link href="/ssr" className="p-4">
            SSR
          </Link>
          <Link href="/csr" className="p-4">
            CSR
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
